In [1]:
import numpy as np

In [5]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
matrix[1,1:3]

array([5, 6])

In [10]:
a = np.array([1,2,3,])
a

array([1, 2, 3])

In [13]:
cond_list = [True,False,True]
a[cond_list]

array([1, 3])

In [19]:
a ** 3

array([ 1,  8, 27])

In [20]:
a[a > 2]

array([3])